version: 2
jobs:
  deploy-s3:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: pip install awscli
      - checkout
      - run:
          name: Deploy S3
          command: |
            aws s3 sync ./public/ s3://${AWS_S3_BUCKET_NAME}/ --delete
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-s3:
          filters:
            branches:
              only: master
